# Generated by Django 4.1.1 on 2022-10-14 04:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=500)),
                ('modelo', models.IntegerField()),
                ('transmision', models.CharField(max_length=200)),
                ('kilometraje', models.IntegerField()),
                ('combustible', models.CharField(max_length=200)),
                ('condicion', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('foto_principal', models.ImageField(upload_to='photos/%Y%m%d/')),
                ('foto_dos', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('foto_tres', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('foto_cuatro', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('foto_cinco', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('es_listado', models.BooleanField(default=True)),
                ('fecha_listado', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listado.categoria')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listado.fabricante')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listado.ubicacion')),
            ],
        ),
    ]
