# Generated by Django 4.1.1 on 2022-10-14 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listado.condicion'),
        ),
    ]
