# Generated by Django 4.1.1 on 2022-10-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0003_alter_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(null=True),
        ),
    ]
