# Generated by Django 4.1.1 on 2022-10-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listado', '0004_producto_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
